# Generated by Django 4.1.3 on 2023-03-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_as',
            field=models.SmallIntegerField(blank=True, choices=[('1', 'Coordinator'), ('2', 'Player')], max_length=1, null=True),
        ),
    ]
