# Generated by Django 4.1.3 on 2023-04-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_login',
            name='game',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game_login',
            name='player',
            field=models.CharField(max_length=100),
        ),
    ]
