# Generated by Django 4.1.3 on 2023-04-16 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_game_login_game_alter_game_login_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='game',
        ),
        migrations.AlterField(
            model_name='game_login',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.game'),
        ),
        migrations.AlterField(
            model_name='game_login',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
