# Generated by Django 4.1.3 on 2023-03-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_register_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_as',
            field=models.IntegerField(choices=[('1', 'Coordinator'), ('2', 'Player')], default=2, max_length=1),
            preserve_default=False,
        ),
    ]
