# Generated by Django 4.1.3 on 2023-04-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_game_password_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
