# Generated by Django 4.1.3 on 2023-04-16 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_level_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_login',
            name='joined_at',
        ),
        migrations.AddField(
            model_name='user',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app.game'),
        ),
        migrations.AlterField(
            model_name='game_login',
            name='game',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='game_login',
            name='player',
            field=models.CharField(max_length=500),
        ),
    ]
