# Generated by Django 4.1.3 on 2023-04-03 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_player_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='coordinator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games_created', to='app.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.game'),
        ),
    ]
