# Generated by Django 4.1.3 on 2023-04-03 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_game_coordinator_alter_user_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app.game'),
        ),
    ]
