# Generated by Django 4.1.3 on 2023-04-16 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_game_login_game_alter_game_login_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.game'),
        ),
    ]
