# Generated by Django 4.1.3 on 2023-04-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_level_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_login',
            old_name='game',
            new_name='games',
        ),
    ]
