# Generated by Django 4.1.3 on 2023-04-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_game_game_login_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='number',
        ),
    ]
