# Generated by Django 4.1.3 on 2023-04-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_level_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='game_level',
            field=models.IntegerField(max_length=1),
        ),
    ]
