# Generated by Django 4.1.3 on 2023-04-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_level_game_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='game_level',
            field=models.IntegerField(),
        ),
    ]
