# Generated by Django 4.1.3 on 2023-04-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_level_game_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_login',
            name='current_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
