# Generated by Django 4.1.3 on 2023-04-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_game_login_current_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_login',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
    ]
