# Generated by Django 4.1.3 on 2023-05-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_game_login_current_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='rules',
        ),
        migrations.AddField(
            model_name='game',
            name='rules',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
