# Generated by Django 4.1.3 on 2023-05-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_level_rules_game_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_login',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
