# Generated by Django 4.1.3 on 2023-05-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_game_login_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_login',
            name='first_completed',
            field=models.BooleanField(default=False),
        ),
    ]
