# Generated by Django 4.1.3 on 2023-06-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_game_login_first_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='password',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='level',
            name='password_result',
        ),
    ]
